language: python

matrix:
  include:
    # perform a linux build
    - services: docker
    # and a mac build
    - os: osx
      language: generic

env:
  global:
    - TWINE_USERNAME=joerick
      # Note: TWINE_PASSWORD is set in Travis settings

script:
  - python -m pip install twine cibuildwheel==1.0.0
  # build the wheels, put them into './wheelhouse'
  - python -m cibuildwheel --output-dir wheelhouse
  # if the release was tagged, upload them to PyPI
  - |
    if [[ $TRAVIS_TAG ]]; then
      python -m twine upload wheelhouse/*.whl
    fi
